version: "3.8"

services:
  kajukenbo-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kajukenbo-website
    ports:
      - "888:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    restart: unless-stopped

